#!/bin/bash

set -e
# set -x
set -o pipefail

function fail() {
  echo "$1"
  exit 1
}

APP_NAME="$1"
[ "$APP_NAME" == "" ] && fail "required: <APP_NAME> params"

[ "$GOOGLE_ACCOUNT_SERVICE_EMAIL" == "" ] && fail "required: <GOOGLE_ACCOUNT_SERVICE> params"
[ "$GOOGLE_PROJECT" == "" ] && fail "required: <GOOGLE_PROJECT> params"
[ "$GOOGLE_APPS_SERVICE_JSON" == "" ] && fail "required: <GOOGLE_APPS_SERVICE_JSON> params"
[ "$FIREBASE_TOKEN" == "" ] && fail "required: <FIREBASE_TOKEN> params"

mkdir -p ~/.googlecloud
# write service account access params
cat <<EOF > ~/.googlecloud/$GOOGLE_PROJECT
${GOOGLE_APPS_SERVICE_JSON}
EOF
cat ~/.googlecloud/$GOOGLE_PROJECT
echo "GOOGLE_ACCOUNT_SERVICE_EMAIL $GOOGLE_ACCOUNT_SERVICE_EMAIL"
echo "GOOGLE_PROJECT $GOOGLE_PROJECT"
echo "gcloud login"
gcloud auth activate-service-account $GOOGLE_ACCOUNT_SERVICE_EMAIL --key-file=$HOME/.googlecloud/$GOOGLE_PROJECT --project $GOOGLE_PROJECT
echo "install nodejs zip unzip"
curl -sL https://deb.nodesource.com/setup_12.x | bash -
apt-get install -y nodejs unzip zip
npm install yaml@1.8.3
npm install -g firebase-tools@7.16.2

FOLDER_PATH="/tmp/apps/${APP_NAME}"
echo "run set_deployment_folder.js"
node .circleci/set_deployment_folder.js $APP_NAME $FOLDER_PATH

echo "cd to: $FOLDER_PATH"
cd $FOLDER_PATH
echo "gcloud builds submit"
gcloud builds submit --config cloudbuild.json ./
firebase deploy --project $GOOGLE_PROJECT --token $FIREBASE_TOKEN
