#!/bin/bash

set -e
# set -x
set -o pipefail

function fail() {
  echo "$1"
  exit 1
}

APP_NAME="$1"
[ "$APP_NAME" == "" ] && fail "required: <APP_NAME> params"

[ "$GOOGLE_ACCOUNT_SERVICE" == "" ] && fail "required: <GOOGLE_ACCOUNT_SERVICE> params"
[ "$GOOGLE_PROJECT" == "" ] && fail "required: <GOOGLE_PROJECT> params"
[ "$GOOGLE_APPS_BACKEND_SERVICE_JSON" == "" ] && fail "required: <GOOGLE_APPS_BACKEND_SERVICE_JSON> params"

# write service account access params
cat <<EOF > ~/.googlecloud/$GOOGLE_PROJECT
$GOOGLE_APPS_BACKEND_SERVICE_JSON
EOF

# gcloud login
gcloud auth activate-service-account $GOOGLE_ACCOUNT_SERVICE --key-file=$HOME/.googlecloud/$GOOGLE_PROJECT --project $GOOGLE_PROJECT

curl -sL https://deb.nodesource.com/setup_12.x | bash -
apt-get install -y nodejs unzip zip
npm install yaml@1.8.3

FOLDER_PATH="/tmp/apps/${APP_NAME}"

node .circleci/set_deployment_folder.js $APP_NAME $FOLDER_PATH

echo "cd to: $FOLDER_PATH"
cd $FOLDER_PATH
echo "gcloud builds submit"
gcloud builds submit --config cloudbuild.json ./
